### ISSUE TITLE
Support date ranges in date picker

### ISSUE THREAD

**Issue by frattaro** [cisco-sbg-ui/atomic-react#1062]
**Is your feature request related to a problem? Please describe.**

As a developer I need to support date ranges in the date picker.

**Describe the solution you'd like**

Gotta look like this:

![image](https://user-images.githubusercontent.com/14955351/143307525-2fd6c8e4-b924-4e5c-93a1-5222bb32d41d.png)

Will need one new prop and an adjustment to another prop.
- `date` needs to support an array of dates.
- `range` needs added, so we know if it's an array, select all the dates between the dates.

**Additional context**

The CSS is already there, the `&__range` class

**Comment by brennarvo** [comment]
> `range` needs added, so we know if it's an array, select all the dates between the dates.

Is there a plan to support an array of dates that aren't in a sequential range in the same date picker component? E.g., a user selecting every other day of the week: `<ADatePicker value={[sunObj, tuesObj, thursObj, satObj]} />`

If not, then I don't think the `range` prop would be necessary given we could do a type check on the `date` prop itself. Then, the `date` component could support either a single date object, or something equivalent to a tuple that is a 2-item array with a starting date and ending date.
