### ISSUE TITLE
Data Table Not Striped

### ISSUE THREAD

**Issue by DarMontou** [cisco-sbg-ui/atomic-react#1106]
**Describe the bug**
The `striped` property for the data table component is not working. It appears to work as expected for the simple table component.

**To Reproduce**

1. Go to https://atomic-react.security.cisco.com/components/data-table
2. Scroll the Usage block until the `ADataTable` and its `striped` property are visible
3. Observe that the table is not striped

**Screenshots**
![Screen Shot 2022-01-11 at 10 11 05 PM](https://user-images.githubusercontent.com/5217225/149062543-b37f98b6-5bb7-40e3-baaf-f775da40d427.png)

**Comment by brennarvo** [comment]
[Atomic's color palette](http://ux-document-lnx/~designer/sbg-ux/components/particles/palette.html#get-coregrays) uses an alternating row color of `#FBFBFB` for Light theme. [The Dusk theme mapping for this hex color](http://ux-document-lnx/~designer/sbg-ux/components/particles/dusk.html#get-style) specifies that it isn't used in alternate table rows, but doesn't provide an alternative. If we can get a hex value for alternating table rows in Dusk, this can be easily implemented.

**Comment by DarMontou** [comment]
Can we use the same values as the simple table component is using?

**Comment by brennarvo** [comment]
`ADataTable` is composed of the `ASimpleTable`. I might be missing something, but there is [currently no striped color for the Dusk simple table](https://atomic-react.security.cisco.com/components/simple-table#usage) (it's currently transparent). If we update the simple table, the data table will also be updated.

**Comment by frattaro** [comment]
Design system does not support striped tables in dusk theme:

http://ux-document-lnx/~designer/demo/demo-page.html
http://ux-document-lnx/~designer/sbg-ux/components/organisms/tables.html
