### ISSUE TITLE
Combobox: consider conditional render of X button

### ISSUE THREAD

**Issue by emmafull** [cisco-sbg-ui/atomic-react#934]
**Describe the bug**
This may be considered an enhancement and not a bug... the X button in the combobox doesn't do anything when there is no input and the menu is closed. Consider conditionally rendering the X button so it's only visible when it does something.

**To Reproduce**
1. Go to https://atomic-react.vercel.app/components/combobox
2. Click on X button in the Usage section Combobox with Objects example when there is no input and the menu is closed
3. Notice nothing happens on click 

**Expected behavior**
X button is not visible when it doesn't do anything (i.e. there is no input and the menu is closed)

**Screenshots**
X button doesn't do anything in this state:
![image](https://user-images.githubusercontent.com/11358963/132878196-8adbe913-518d-46a1-b41d-aac0f6e5f611.png)

**Environment (please complete the following information):**
 - Device: Desktop
 - OS: macOS
 - Browser Firefox
 - Version 92

**Comment by frattaro** [comment]
Can do:
```
<ACombobox {...comboboxProps}
  clearable={value} />
```

Not sure why whether the dropdown is open would impact clearability
