### ISSUE TITLE
Scrolling tabs focused tab display issue

### ISSUE THREAD

**Issue by frattaro** [cisco-sbg-ui/atomic-react#987]
**Describe the bug**

When a tab in scrolling tabs is focused, the top border isn't appearing: 
![image](https://user-images.githubusercontent.com/14955351/139271956-63446b12-df14-447b-a104-78734573aaeb.png)

**To Reproduce**

Go here: https://atomic-react.security.cisco.com/components/tab#scrolling
click a tab, see missing top border

**Expected behavior**

The top border should be visible

**Additional context**

`.a-tab-group__tab-content` needs 1px top padding. After the change is made, the github action workflow `Update Snapshots` needs run on the published branch, and that should update the visual regression test assets

**Comment by MizuhoOkimoto** [comment]
Hi, may I work on it? I appreciate it if you assign it to me.

**Comment by frattaro** [comment]
@MizuhoOkimoto Everything is up for grabs, feel free to assign yourself to anything you'd like

**Comment by MizuhoOkimoto** [comment]
Thank you for your reply! I changed the padding so that I will make a PR soon. I'm new here, so I'm not sure how to work for the "Additional context". Could you please explain what I should do?

**Comment by frattaro** [comment]
So when you add the PR the tests will run and should fail, because the snapshot images will be different. Those snapshot images are updated via github action.

I took a screenshot from over in the `Actions` tab. On the left side, clicking "Update Snapshots" and then on the right side choosing your branch. When the workflow runs, it'll update the snapshots and commit the change to the branch you selected.

![image](https://user-images.githubusercontent.com/14955351/139561160-fa544776-d2e4-4df3-995d-82a3a2e8f57d.png)

**Comment by MizuhoOkimoto** [comment]
Thank you for your detailed explanation! I made a PR, and the snapshot is updating now!
