### ISSUE TITLE
Sidebar

### ISSUE THREAD

**Issue by frattaro** [cisco-sbg-ui/atomic-react#991]
**Is your feature request related to a problem? Please describe.**

As a developer, I need a react implementation of the atomic sidebar: http://ux-document-lnx/~designer/sbg-ux/components/organisms/sidebar.html

**Describe the solution you'd like**

This component renders in-flow (pushes content to the side when expanded), which makes it difficult integrate into layouts without custom CSS. Not only is the variable width a problem, but it's also a vertical scrolling container that doesn't scroll with the page. Ideally it'd be something you can drop into a layout and not worry about it.

**Additional context**

Shouldn't need much of an API -- a `collapsed` prop. Appears to minimally need `ASidebar`, `ASidebarHeader`, `ASidebarIcon`.

**Comment by vdineva** [comment]
We have such a component in the react-components repo. It was created in this PR: https://github.com/advthreat/react-components/pull/140

Closing this issue
